/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlgeriaRouteImport } from './routes/admin/algeria'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as OffersOfferIdRouteImport } from './routes/offers/$offerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlgeriaRoute = AdminAlgeriaRouteImport.update({
  id: '/admin/algeria',
  path: '/admin/algeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/admin/footer',
  path: '/admin/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersOfferIdRoute = OffersOfferIdRouteImport.update({
  id: '/$offerId',
  path: '/$offerId',
  getParentRoute: () => OffersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discounts': typeof DiscountsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/perfumes': typeof PerfumesRoute
  '/admin/algeria': typeof AdminAlgeriaRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discounts': typeof DiscountsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/perfumes': typeof PerfumesRoute
  '/admin/algeria': typeof AdminAlgeriaRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discounts': typeof DiscountsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/perfumes': typeof PerfumesRoute
  '/admin/algeria': typeof AdminAlgeriaRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/discounts'
    | '/login'
    | '/offers'
    | '/perfumes'
    | '/admin/algeria'
    | '/admin/contacts'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/footer'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/settings'
    | '/offers/$offerId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/discounts'
    | '/login'
    | '/offers'
    | '/perfumes'
    | '/admin/algeria'
    | '/admin/contacts'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/footer'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/settings'
    | '/offers/$offerId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/discounts'
    | '/login'
    | '/offers'
    | '/perfumes'
    | '/admin/algeria'
    | '/admin/contacts'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/footer'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/settings'
    | '/offers/$offerId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DiscountsRoute: typeof DiscountsRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRouteWithChildren
  PerfumesRoute: typeof PerfumesRoute
  AdminAlgeriaRoute: typeof AdminAlgeriaRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/algeria': {
      id: '/admin/algeria'
      path: '/admin/algeria'
      fullPath: '/admin/algeria'
      preLoaderRoute: typeof AdminAlgeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/admin/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$offerId': {
      id: '/offers/$offerId'
      path: '/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof OffersOfferIdRouteImport
      parentRoute: typeof OffersRoute
    }
  }
}

interface OffersRouteChildren {
  OffersOfferIdRoute: typeof OffersOfferIdRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersOfferIdRoute: OffersOfferIdRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DiscountsRoute: DiscountsRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRouteWithChildren,
  PerfumesRoute: PerfumesRoute,
  AdminAlgeriaRoute: AdminAlgeriaRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
